// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFH0dsKCfLwjAu1VZ5OT9AKYqKPAvMilc',
    appId: '1:634302941979:web:b429aba2c8c07e8ead61be',
    messagingSenderId: '634302941979',
    projectId: 'cafe-app-d12eb',
    authDomain: 'cafe-app-d12eb.firebaseapp.com',
    storageBucket: 'cafe-app-d12eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzUWj6HQe1vHZ1JSOPRxdECvi-4GN6kMA',
    appId: '1:634302941979:android:bea511a673b18770ad61be',
    messagingSenderId: '634302941979',
    projectId: 'cafe-app-d12eb',
    storageBucket: 'cafe-app-d12eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVeOaDGhTae7_dQZsV5D_Q_ntAmARE4M8',
    appId: '1:634302941979:ios:b646b74ac113f764ad61be',
    messagingSenderId: '634302941979',
    projectId: 'cafe-app-d12eb',
    storageBucket: 'cafe-app-d12eb.appspot.com',
    iosBundleId: 'com.example.cafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVeOaDGhTae7_dQZsV5D_Q_ntAmARE4M8',
    appId: '1:634302941979:ios:779d0715cbe29fb2ad61be',
    messagingSenderId: '634302941979',
    projectId: 'cafe-app-d12eb',
    storageBucket: 'cafe-app-d12eb.appspot.com',
    iosBundleId: 'com.example.cafeApp.RunnerTests',
  );
}
